# -*- coding: utf-8 -*-
"""ModeloAM_SF

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Vpx3Y6kzrZsUSV-AET2Z_qD0n7uWH2l
"""

import pandas as pd
from sklearn.model_selection import train_test_split

targets = ['Exclusividade', 'Autenticidade', 'Funcionalismo', 'Localismo']

X = df.drop(columns=targets)
y = df[targets]

x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import Ridge, Lasso
from sklearn.svm import SVR
from sklearn.metrics import r2_score
import numpy as np

modelos = {
    'RandomForest': RandomForestRegressor(random_state=42),
    'GradientBoosting': GradientBoostingRegressor(random_state=42),
    'Ridge': Ridge(),
    'Lasso': Lasso(),
    'SVR': SVR()
}

for nome, base in modelos.items():
    model = MultiOutputRegressor(base)
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    r2 = np.mean([
        r2_score(y_test.iloc[:, i], y_pred[:, i])
        for i in range(y_test.shape[1])
    ])
    print(f"{nome} — R² médio: {r2:.3f}")

from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge

param_grid = {'alpha': [0.01, 0.1, 1, 10, 100]}
ridge = Ridge()
grid = GridSearchCV(ridge, param_grid, cv=5, scoring='r2')
grid.fit(x_train, y_train)

print("Melhor alpha:", grid.best_params_)
print("Melhor R² médio (CV):", grid.best_score_)

from sklearn.linear_model import ElasticNet
from sklearn.model_selection import GridSearchCV

param_grid = {
    'alpha': [0.01, 0.1, 1, 10],
    'l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9]
}

grid = GridSearchCV(ElasticNet(), param_grid, cv=5, scoring='r2')
grid.fit(x_train, y_train)

print("Melhores parâmetros:", grid.best_params_)
print("Melhor R² médio (CV):", grid.best_score_)

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import Ridge

ridge_best = Ridge(alpha=0.1).fit(x_train, y_train)

coef_media = np.abs(ridge_best.coef_).mean(axis=0)
indices = np.argsort(coef_media)[::-1]

plt.figure(figsize=(8,6))
sns.barplot(x=coef_media[indices][:10], y=X.columns[indices][:10])
plt.xlabel('Importância média (|coef|)')
plt.ylabel('Variável visual')
plt.title('Top 10 variáveis mais influentes nas dimensões simbólicas')
plt.show()

from sklearn.metrics import r2_score

y_pred = ridge_best.predict(x_test)
for i, col in enumerate(y.columns):
    print(f"{col} — R² individual: {r2_score(y_test[col], y_pred[:, i]):.3f}")

from sklearn.linear_model import ElasticNet

model_final = ElasticNet(alpha=0.01, l1_ratio=0.1, random_state=42)
model_final.fit(x_train, y_train)

linhas = []
for i, col in enumerate(targets):
    r2  = r2_score(y_test[col], y_pred[:, i])
    rmse = np.sqrt(mean_squared_error(y_test[col], y_pred[:, i]))  # corrigido
    linhas.append({"Dimensão": col, "R2": r2, "RMSE": rmse})

df_metricas_reg = pd.DataFrame(linhas)
df_metricas_reg.loc["MÉDIA"] = ["—", df_metricas_reg["R2"].mean(), df_metricas_reg["RMSE"].mean()]
df_metricas_reg

# ----- 3) DISCRETIZAÇÃO EM 3 CLASSES (baixo/médio/alto) COM BASE NOS QUANTIS DO CONJUNTO DE TREINO -----
def discretizar_por_quantis(serie_treino, serie_teste, n_classes=3):
    # limites com base no treino (quantis iguais)
    qs = np.linspace(0, 1, n_classes+1)
    bins = serie_treino.quantile(qs).values
    # garantir estritamente crescente (evita empates quando há muitos valores iguais)
    bins = np.unique(bins)
    # se der menos de 4 limites (ex.: valores repetidos), faz bins equilibrados pelo min/max
    if bins.size < n_classes+1:
        bins = np.linspace(serie_treino.min()-1e-9, serie_treino.max()+1e-9, n_classes+1)
    # rótulos
    labels = [0,1,2][:len(bins)-1]
    y_tr_cls = pd.cut(serie_treino, bins=bins, labels=labels, include_lowest=True).astype(int)
    y_te_cls = pd.cut(serie_teste,  bins=bins, labels=labels, include_lowest=True).astype(int)
    return y_tr_cls, y_te_cls, bins

# gera predições discretizadas por dimensão
accs = []
cms_paths = []
Path("metricas_figs").mkdir(exist_ok=True)

for i, col in enumerate(targets):
    # classes verdadeiras (treino e teste) para definir bins e aplicar
    _, y_test_cls, bins = discretizar_por_quantis(y_train[col], y_test[col])

    # discretiza as previsões usando os MESMOS bins do treino
    y_pred_series = pd.Series(y_pred[:, i], index=y_test.index, name=f"pred_{col}")
    y_pred_cls = pd.cut(y_pred_series, bins=bins, labels=[0,1,2][:len(bins)-1], include_lowest=True).astype(int)

    # acurácia
    acc = accuracy_score(y_test_cls, y_pred_cls)
    accs.append({"Dimensão": col, "Acurácia (3 classes)": acc})

    # matriz de confusão
    cm = confusion_matrix(y_test_cls, y_pred_cls, labels=[0,1,2])

    # ----- 4) PLOT DA MATRIZ DE CONFUSÃO (matplotlib puro) -----
    fig, ax = plt.subplots(figsize=(5,4))
    im = ax.imshow(cm)  # sem estilo/cor específica (requisito)
    ax.set_title(f"Matriz de Confusão – {col} (0=baixo,1=médio,2=alto)")
    ax.set_xlabel("Previsto")
    ax.set_ylabel("Verdadeiro")
    ax.set_xticks([0,1,2]); ax.set_yticks([0,1,2])

    # anotações das contagens
    for r in range(cm.shape[0]):
        for c in range(cm.shape[1]):
            ax.text(c, r, cm[r, c], ha="center", va="center")

    fig.tight_layout()
    out_path = Path("metricas_figs") / f"confusion_{col}.png"
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.show()
    cms_paths.append(str(out_path))

# tabela de classificação (acurácia) por dimensão
df_metricas_cls = pd.DataFrame(accs)
df_metricas_cls.loc["MÉDIA"] = ["—", df_metricas_cls["Acurácia (3 classes)"].mean()]
df_metricas_cls, cms_paths

import joblib, json, sklearn, numpy as np, pandas as pd, platform, sys
from pathlib import Path

# listas de colunas (ordem importa!)
FEATURES = list(X.columns)
TARGETS  = list(y.columns)

# empacote o modelo e infos mínimas
bundle = {
    "model": model_final,        # ElasticNet multi-alvo treinado
    "features": FEATURES,        # ordem esperada de colunas
    "targets": TARGETS,          # nomes das saídas
}

Path("artifacts").mkdir(exist_ok=True)
joblib.dump(bundle, "artifacts/elasticnet_multitarget.joblib")

# versões p/ reprodutibilidade
meta = {
    "python": sys.version,
    "platform": platform.platform(),
    "sklearn": sklearn.__version__,
    "pandas": pd.__version__,
    "numpy": np.__version__,
    "model_type": "ElasticNet-multioutput",
    "params": {"alpha": 0.01, "l1_ratio": 0.1, "random_state": 42}
}
with open("artifacts/metadata.json", "w", encoding="utf-8") as f:
    json.dump(meta, f, ensure_ascii=False, indent=2)

import joblib, pandas as pd

def load_model(path="artifacts/elasticnet_multitarget.joblib"):
    bundle = joblib.load(path)
    return bundle

def predict_continuo(df_novo, bundle):
    X_new = df_novo.reindex(columns=bundle["features"], fill_value=0)
    y_hat = bundle["model"].predict(X_new)
    return pd.DataFrame(y_hat, columns=bundle["targets"], index=df_novo.index)

# Exemplo de uso:
# bundle = load_model()
# y_pred = predict_continuo(df_novo, bundle)

import joblib
bundle = joblib.load("artifacts/elasticnet_multitarget.joblib")
print(bundle.keys())

joblib.dump(bundle, "artifacts/elasticnet_multitarget.joblib")

from google.colab import files
files.download("artifacts/elasticnet_multitarget.joblib")